### ISSUE TITLE
Many selects on a page makes stop script

### ISSUE THREAD

**Issue by lwen3** [truckingsim/Ajax-Bootstrap-Select#103]
Hi, I am new and congratulations for this excelent plugin.
I am using it, but now I have hundreds of ajax selectpicker and when loading page, it lasts long time to load it.
I saw that the command:
$('.selectpicker').selectpicker().filter('.with-ajax').ajaxSelectPicker(options);
is the problem. 
How can I optimize it? Any suggestions?

Tks,

Lee

**Comment by truckingsim** [comment]
any time you have that many selects its going to be select. That is actually coming from selectpicker because it needs to replace the original selects with its own.  That means it's injecting a lot of DOM elements and replacing the original selects.  All that is very expensive.  You have a couple options:

First is, do they all really need to be on one page?  If not break the process into multiple pages.  If they all REALLY need to be on one page then you can try only initializing them once they are in the viewport.  This is more difficult and you would need to figure out how to do it, but it should be doable.

Either way there's not much Ajax bootstrap select can do so marking this as won't fix, and closing.  Let me know if you have any other questions.
