### ISSUE TITLE
By default show some options in the selectpicker

### ISSUE THREAD

**Issue by bsurendrakumar** [truckingsim/Ajax-Bootstrap-Select#105]
Hi,

I'm using this plugin to fetch the data based on the text entered in the search box. I'm facing one issue like by default the select picker is not showing any options, once the user types in then only user is able to see the options.

Is there any setting like showing some options in the select picker (through AJAX) by default?

**Comment by truckingsim** [comment]
If you put options in the select on page load they will show up in the picker, but no there is no way right now to have options loaded in through ajax (that's built in) without typing.

**Comment by markcarver** [comment]
You have to add the "default options" to the HTML initially when the page is rendered/plugin loaded. That is how the parent project (bootstrap-select) works.

Also, the ability to [programmatically add/remove items](https://silviomoreto.github.io/bootstrap-select/methods/#selectpickerrefresh) already exists in the parent project, which is what this project uses.

---

Closing since this falls outside the scope of this project.

**Comment by bsurendrakumar** [comment]
Hi @truckingsim, @markcarver 

Thanks for your response.

For now, I solved this issue by triggering a **keyup** event on the search field.

```js
$('.bs-searchbox .form-control').trigger('keyup');
```

**Comment by ksidibe** [comment]
@markcarver,
This is not an "invalid" issue. Being able to have some options displayed before event typing anything is the right behavior. It is the behavior of bs-select which this plugin (which is very useful) has altered. One would generally expect an "Add-on" to augment the functionality of the parent plugin and not alter it in such a major way.
I do hope you guys would reconsider addressing this issue.
Thank you.
