### ISSUE TITLE
Limit results and scroll to load more

### ISSUE THREAD

**Issue by callumstrubi** [truckingsim/Ajax-Bootstrap-Select#110]
This is best exemplified with the select2 https://select2.github.io/examples.html#data-ajax

You should be able to limit a returned dataset and load more dynamically as the user scrolls to improve performance. If a user searches "Dave" and there are 1800 "Dave"s registered in your dataset, you wouldn't want to return 1800 results to the client. 

I note that 2.0.0 roadmap has existed for some time and has some thought to this - I think it deserves to be an issue of it's own.

Detecting Scroll:
You could do this using the scroll position, or you create a ```<div class="loadMore"></div>``` which is at the end of the select results, when the user scrolls such that the div is visible, trigger the loading of the next page of data. Just an idea.

**Comment by truckingsim** [comment]
So we consider limiting results to be the servers job, not the plugins.  That may change in the future but its unlikely.  I don't see a real world where you need paging in this plugin.  If there are that many results that are identical, then type a little more to narrow it.  Instead of doing simple indexOf or LIMIT SQL searches, do fuzzy searches on the server.  

I'm not likely to add this to the plugin, you're welcome to try and convince me of a really good reason for it but it also means we have to deal with paging data and that I'm not thrilled about.  We don't control the actual select that's rendered.  We give that control back to `bootstrap-select` once we are done updating the `options` in the original `select` tag.  Its not simple to just add a div because we aren't the ones rendering the custom html, `bootstrap-select` is.

**Comment by markcarver** [comment]
This duplicates #32

**Comment by markcarver** [comment]
> means we have to deal with paging data and that I'm not thrilled about

Neither am I.

> We don't control the actual select that's rendered.

Yep. This, unfortunately, goes outside the scope of this project.

**Comment by callumstrubi** [comment]
It's a matter of user understanding, if a user searches "Dave" and gets 10 results, doesn't find the "Dave" they are looking for, they may assume that "Dave" is simply not registered in the database. Your situation of searching more to narrow assumes the user understands their results are being limited for optimisation, not because of lack of data. 

An alternative would be having a way of displaying "Showing 10 of 1500 possible matches" at the bottom of the rendered dropdown. This way you don't have to do paging, but you do tell the user to filter some more to get the specific "Dave" they are looking for.

Another use case is for selects that are initialised with ```options.emptyRequest = true``` to give the user the standard select workflow of opening the select and scrolling through potential options.

**Comment by markcarver** [comment]
I have a feeling this isn't going away. I'll re-open, but only as a discussion to see how feasible this truly would be.

**Comment by markcarver** [comment]
No promises. Paging, especially when dealing with AJAX/autocomplete, can be a huge PITA.

**Comment by callumstrubi** [comment]
Well, as you're handing off rendering to bootstrap-select and it has no dropdown scrolling events added in you'd probably have to hack in your own event trigger or your own markup - neither are ideal. You push in the statusContainer, so you could use that to display the "Showing X of Y possible matches" text which is the half way house of not much work, but clarifying the situation for the user.

**Comment by markcarver** [comment]
Anything is possible. Yes, we could separate message for the status container; that isn't the issue.

The issue revolves around handling scrolling + adding/removing elements based on scroll.

I can assure you, this topic is far more complicated than you may realize.

**Comment by callumstrubi** [comment]
So if I'm write the cache must store an array of results associated with the search string entered to provide those results, when you scroll you don't need to remove the previous results, just append the new ones (so pull your previous X results for search STR and append Y results). Use a method similar to dataTables where you have to pass back the "page" number (or "draw" in their case) which can be used to detect whether you already have cached results for page N.

**Comment by markcarver** [comment]
> when you scroll you don't need to remove the previous results

Common misconception.

To do infinite scrolling, properly, one has to be conscientious about what the impact of adding DOM elements to the page will be. Even more so if there any assets that require storing the resource along with it, like images.

Simply "just appending" DOM elements can have serious animation performance issues if there is any transitions/transforms involved on the dropdown or its items.

Never mind actual [browser](http://stackoverflow.com/questions/16637530) or [device](https://engineering.linkedin.com/linkedin-ipad-5-techniques-smooth-infinite-scrolling-html5) limitations.

However, the real performance hit is one that many don't even consider: adding DOM elements can actually impact **other** JS loaded on the page (which also traverses said DOM). If those JS plugins/apps not optimized properly (which many plug 'n play ones aren't because they only think of themselves), this change would likely and inadvertently cause more (harder to track) problems than it originally intended to solve.

This is actually why this project exists in the first place. If you have ever attempted to load the parent plugin where a select element has hundred/thousands of options, it can lock up the browser (or appear to rather) because it takes so long for all the DOM manipulation to complete.

If this were something like twitter.com or facebook.com, where we had complete control over the entire DOM, then appending would likely be fine (but even they eventually remove DOM elements to account for above mentioned browser/device limitations).

This is a plugin, we don't control the entire DOM, just parts of it. We would most certainly have to manage adding/removing items based on current scroll position.

I actually have some experience on this topic as I have actually attempted to implemented this in a JS based git patch review tool where the DOM is manipulated constantly to handle a multitude of performance related issues when dealing with "varying content" like this:
https://github.com/unicorn-fail/dreditor-ui/blob/master/src/js/Infinity.js
https://github.com/unicorn-fail/dreditor-ui/blob/master/src/js/InfinityItem.js

Like I said, this is far more complicated than you realize.

**Comment by truckingsim** [comment]
Also to add on to this we don't actually control any of the dom other than the options in the original select which is hidden.  Bootstrap-select even renders the the textarea for search, we just strip all their event listeners and add our own to take control.  When we get results we replace the options in the select and call refresh on bootstrap-select.  We never render visible dom contents onto the page, bootstrap-select does.

So knowing that, in addition to having to add rendering, we would also have to trigger the right event on select because bootstrap-select wouldn't be rendering the rendered option we would, so we would have to trigger the change event.  On a mult-select we would have to render the checkbox denoting this was selected.  It's just out of the purview of this plugin which is meant as essentially an add-on for bootstrap-select, not a replacement.

**Comment by truckingsim** [comment]
I'm going to close this if you want to limit the results shown either do that on the server or in the `preprocessData` option.
