### ISSUE TITLE
Unable to see any live example of this addon

### ISSUE THREAD

**Issue by vibs2006** [truckingsim/Ajax-Bootstrap-Select#128]
Can anyone guide me to see a live example (working demo) of this plugin implemented ?

**Comment by truckingsim** [comment]
There is no live example because for the search to work like it does on a server it requires a server running.  Since that is needed we can't use github pages for that.  I updated the example folder to have a node server example: https://github.com/truckingsim/Ajax-Bootstrap-Select/tree/master/example

You can see how to run that in the example.  After you run `npm install` then `npm start` in the example directory, go to `localhost:8080` in your browser to see it work.  

That's about as easy as it's going to get atm, you don't need php for that example only node.

**Comment by scrnjakovic** [comment]
You don't need a server, you can use mockajax.

**Comment by necmettin** [comment]
Any user new to any library would like to see a *running* example, a live demo if you will, one that s/he wouldn’t need to set up using nom or mockajax or anything, one that they can see running without any effort, is all I’m saying.

**Comment by scrnjakovic** [comment]
You do realize mockajax would just supply data as if it was sent back by the server, so you don't actually need a server, which is why @truckingsim said there was no demo? Hence, it would be **running example** or working example, if you will. Having a demo of backend returning data is not something this plugin should be concerned with. It's just JSON data, which, by the way, you'd get to see the structure of in mockajax example...

> Any user new to any library would like to see a _running_ example, a live demo if you will, one that s/he wouldn’t need to set up using nom or mockajax or anything, one that they can see running without any effort, is all I’m saying.
