### ISSUE TITLE
Invoke request when opening selectpicker (empty input)

### ISSUE THREAD

**Issue by EcoFreak** [truckingsim/Ajax-Bootstrap-Select#140]
Hello guys,

Is it possible to, when opening the input for the first time, to for the execution of the query?
In some cases it's useful to show some options straight away without the user input.

Thanks ;)

**Comment by truckingsim** [comment]
You should send the default options down as options in the initial html select.  

So instead of sending:

```html
<select></select>
```

You would send:

```html
<select>
    <option>Initial Option</option>
</select>
```

I don't plan on adding an option for an initial query.

**Comment by bradmac** [comment]
FYI, I needed this because the state management didnt work propertly when using server rendered options with ajax search. So I just stuck this line:
```
this.selectpicker.$searchbox.trigger("keyup");
```

into AjaxBootstrapSelect.prototype.init = function () {

There's probably a better way of doing it. I think a config option to do that would be a nice to have.

**Comment by markcarver** [comment]
No, see comment here: https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/171#issuecomment-534316319
