### ISSUE TITLE
How to have a deselect option?

### ISSUE THREAD

**Issue by martabelfm** [truckingsim/Ajax-Bootstrap-Select#174]
When selection is done, and I would like to select empty option, as nothing selected, how could this be done?

**Comment by markcarver** [comment]
```js
$('select').selectpicker('val', '');
```

**Comment by ppazos** [comment]
@markhalliwell I'm actually selection an empty option manually and the previously selected value appears on the select. If I try to execute that code in the changed.bs.select I get the error "too much recursion", because the selectpicker('val', '') triggers also the event.

How can I select an empty option and make an empty string appear on the select?

BTW if I remove the ajax plugin and keep the bootstrap-select, selecting the empty option works OK.
