### ISSUE TITLE
Options via data attributes

### ISSUE THREAD

**Issue by Rash96** [truckingsim/Ajax-Bootstrap-Select#46]
I want to pass options via data attributes
```html
<select name="GLOBALSUBJID" class="form-control select-picker" 
						data-abs-locale-empty-title="Предмет не выбран"
						data-abs-locale-status-searching="Поиск...">
					</select>
```
but strings don't change, if through the Javascript options object then all is well.

This problem with locale only

**Comment by truckingsim** [comment]
@Rash96 sorry i haven't responded will try and take a look at this, this weekend.

**Comment by Rash96** [comment]
@truckingsim Thank you

**Comment by truckingsim** [comment]
@Rash96 I just pushed up a fix and rebuilt the dist file.  Can you take the dist file in the master branch and give it a shot? If it works I'll do a new release with that fix.

**Comment by markcarver** [comment]
@truckingsim, the commit seems like a hack for jQuery < 1.6 (which introduced camelCasing data keys).

There is already code below what was committed that (should have) handled the overrides automatically: https://github.com/truckingsim/Ajax-Bootstrap-Select/commit/9d889a8cc496c49da92312d59df92820adac0b51#diff-363cba4658af6719eba371f4899de525R243

**Comment by markcarver** [comment]
Also, why was this bumped to 1.4.0? Isn't this just a bug fix?

**Comment by truckingsim** [comment]
I bumped it to 1.4.0 because I felt like it changed how the keys were handled.  Even though it fixes it I felt like it had the possibility to possibly change expected behaiviour for someone. So I decided to do a minor version bump, that can be changed easily though since i haven't actually done a tag.


Also this fixes the data attributes not working.  It wasn't about loading in a different locale through a file, or even using the locale option when instantiating the instance through .ajaxSelectPicker().  The data attribute was broke, even in jQuery 1.9.  It was happening in our index.php example file with his example.

**Comment by markcarver** [comment]
I see what you're talking about now (about this issue). I think we can do a patch version bump instead, it shouldn't affect anything (as it's not really working in the first place).

In an effort to work with the existing code, I took a look at how the data attributes are expanded into the options object in the first place. I'd much prefer to introduce a `flattenedOptions` array that will automatically squash the options as needed (in this case, locale).

I'll commit shortly.

**Comment by markcarver** [comment]
@truckingsim, finished with the commit and build, let me know what you think.

**Comment by truckingsim** [comment]
Like your solution much better.  Thanks for cleaning that up.  @rash96 give it a try but I'm going to do a full release.  I'm confident this is fixed.

**Comment by Rash96** [comment]
@truckingsim, I have checked, it works now. Thank you!
