### ISSUE TITLE
Best way to clear Currently Selected?

### ISSUE THREAD

**Issue by schmoove** [truckingsim/Ajax-Bootstrap-Select#52]
I've read through the code but unsure what the best approach is to programmatically clear the Currently Selected options (effectively reset the plugin).

I can't set preserveSelected = false because I do need to retain selected options between searches. But once the form is submitted (via Ajax) I need to reset everything.

I suspect I can use AjaxBootstrapSelectList.prototype.replaceOptions with a blank value, but is that the best approach?

**Comment by truckingsim** [comment]
So the way Ajax-Bootstrap-Select works is it only takes over the select picker when its rendering options.  After that control is given back to Bootstrap-Select.  So for instance:

`$('select').val('').selectpicker('refresh')` would reset the select picker back to the first value.

For an example of this, here's a fiddle: [https://jsfiddle.net/jefffan24/wj2z31br/](fiddle)

If you type `la` then choose an option that is not Lacy (she should be the first), then after 3 seconds you will see it switch to lacy.  This happens because lacy is the first option, and that's what .val('') will reset to.  I don't know of a way to actually reset the select to no options selected without actually getting rid of all the options inside with something like:

`$('select').html('').selectpicker('refresh');`.  Ajax-Select-Picker won't pick this up so it won't show the `Start typing a search query` message.

I hope this answers your question.  If all else fails you can try destroying the select when you need to truly reset it with something like this: [fiddle](https://jsfiddle.net/jefffan24/Lre5z2ow/).

Here you can choose any option, after 3 seconds it completely replaces the select.


Let me know if there's anything else I can help with.

**Comment by schmoove** [comment]
Thanks for the quick response Adam!

It indeed clears the selection (ie no tick), but when using a multiple
select element, the "Currently Selected" selection remains, and will still
post that selection if the form is submitted.

[image: Inline images 1]

I've updated the fiddle to demonstrate. This is because the optgroup with
the selection remains in the original select element?

[image: Inline images 2]

Not sure if this is a bug or not, but obviously can cause some confusion
when submitting the form several times with different selections.

Ryan


[image: Ryan Marshall - CEO / Founder | Syngency]
Cell: (415) 996 6179 Email: ryan@syngency.com www.syngency.com

[image: Facebook]
<http://t.sidekickopen18.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QBs6PW8rllpW8q-f_4W5v79jl56dw5qf1RpFvH02?t=http%3A%2F%2Fwww.facebook.com%2Fsyngency&si=4885673537961984&pi=49834b52-6aa2-48a1-dd27-aedbb5191d74>
[image:
Twitter]
<http://t.sidekickopen18.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QBs6PW8rllpW8q-f_4W5v79jl56dw5qf1RpFvH02?t=http%3A%2F%2Fwww.twitter.com%2Fsyngency&si=4885673537961984&pi=49834b52-6aa2-48a1-dd27-aedbb5191d74>
<http://t.sidekickopen18.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QBs6PW8rllpW8q-f_4W5v79jl56dw5qf1RpFvH02?t=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fsyngency&si=4885673537961984&pi=49834b52-6aa2-48a1-dd27-aedbb5191d74>

**Comment by truckingsim** [comment]
Can't see the images in the email response but for a multi select use `.val([])` instead of an empty string to reset the select.

**Comment by schmoove** [comment]
Sorry- I updated the comment (wont use email reply again!) so you can see what I mean, and I've updated the fiddle to use `.val([])` but still having the same issue.

**Comment by truckingsim** [comment]
Try this: [fiddle](https://jsfiddle.net/jefffan24/wj2z31br/3/)

It manually calls the listener which updates our currently selected elements, we shouldn't have to do this but it seems to be working with a multi select.


**Note for anyone else who reads this:**  for a multi select this method won't work because there's no way to not select something.  Resetting the selection only changes the selection to the first element.  So for single elements to remove preseveSelected elements you will have to destroy the instance of the select as mentioned at the end of the following comment:  https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/52#issuecomment-133524115.

**Comment by schmoove** [comment]
Ok that seems to have solved it. Thanks for your help Adam!

**Comment by truckingsim** [comment]
Awesome, gonna close this one.  If you run into anything else please create a new issue!
