### ISSUE TITLE
plugin.lastRequest.jqXHR.abort() never reached

### ISSUE THREAD

**Issue by christophe** [truckingsim/Ajax-Bootstrap-Select#62]
Hi there and thank you for this wonderful plugin!

However, I have found a small flaw:

While you have planned for previous requests to be aborted when a new one is created, your implementation does not work because you store the last request only on completion (in the always() handler).

Therefore, if it's still running when the next request is created, it is not aborted because it has not yet been stored in plugin.lastRequest.

Thanks,

Christophe

**Comment by oscarjlep** [comment]
This issue is still true. When you have long query (taking ~3 seconds to finish) and write single letter "m", wait 500ms and write "c donalds", you finally get list of all "m" letters but they register to search "mc donalds". When you try some other search and try "mc donalds" again it simply lists previous wrongs results.

Currently needs implementing of forced clearing of results.

**Comment by truckingsim** [comment]
Considering the world is moving towards fetch, and fetch currently doesn't have a way to abort, I'm probably going to add a debounce option for version 2.0.0.  This isn't a guarantee but this will allow for you to not send the request until the user stops typing for X milliseconds.  Where you define X as an option you pass in.
